### ISSUE TITLE
Error when running catkin_make (Could NOT find orunav_msgs (missing: orunav_msgs_DIR))

### ISSUE THREAD

**Issue by asuleyman** [hoangcuongbk80/Pallet-Detection#1]
-- +++ processing catkin package: 'orunav_pallet_detection_sdf'
-- ==> add_subdirectory(Pallet-Detection/orunav_pallet_detection_sdf)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Could NOT find orunav_msgs (missing: orunav_msgs_DIR)
-- Could not find the required component 'orunav_msgs'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "orunav_msgs" with
  any of the following names:

    orunav_msgsConfig.cmake
    orunav_msgs-config.cmake

  Add the installation prefix of "orunav_msgs" to CMAKE_PREFIX_PATH or set
  "orunav_msgs_DIR" to a directory containing one of the above files.  If
  "orunav_msgs" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  Pallet-Detection/orunav_pallet_detection_sdf/CMakeLists.txt:5 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/ahmed/catkin_ws2/build/CMakeFiles/CMakeOutput.log".
See also "/home/ahmed/catkin_ws2/build/CMakeFiles/CMakeError.log".
make: *** [Makefile:320: cmake_check_build_system] Error 1

**Comment by hoangcuongbk80** [comment]
This repo is a part of [this project](https://github.com/OrebroUniversity/navigation_oru-release)
You can run [the launch file](https://github.com/OrebroUniversity/navigation_oru-release/blob/master/orunav_pallet_detection_sdf/launch/pallet_detection_standalone.launch)

**Comment by asuleyman** [comment]
Thank you for response.
I want to use this project to detect pallets in an autonomous forklift. My data would be in format of cloud point taked from sick Visionary-T camera.
I run the cloned the navigation_oru and launched the file wich resulted in few topics being published like OBBs and filtered_points.
how can I view the results I tried to read messages on topics but it seems to be empty. Any tips ?
